### ISSUE TITLE
Z-axis acceleration in spite of being still

### ISSUE THREAD

**Issue by martin-velas** [ENSTABretagneRobotics/sbg_ros_driver#1]
Hi!
First of all - thanks for your great work! I'm trying to use your driver and it looks to be working (according to the `rostopic echo` and `rviz` visualization) except the acceleration in Z-axis which is constantly around -9.7 for sensor **lying still** on my desk. This is the output of ros echo:
```
header: 
  seq: 13202
  stamp: 
    secs: 1491219289
    nsecs: 732971334
  frame_id: map
orientation: 
  x: -0.000194159161765
  y: -0.00108367542271
  z: -0.967581689358
  w: -0.25255587697
orientation_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
angular_velocity: 
  x: -0.00231326837093
  y: 0.000343044259353
  z: -0.00297229643911
angular_velocity_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
linear_acceleration: 
  x: 0.0124550322071
  y: -0.0125222699717
  z: -9.78081607819
linear_acceleration_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
```

When I move with IMU, all other values changes accordingly just fine.

Do you have any tips for fixing this?
Thanks, Matin.
